// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uifoveurtxcsbdfvrigd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpZm92ZXVydHhjc2JkZnZyaWdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxODMyNTMsImV4cCI6MjA1Nzc1OTI1M30.hdYWNqJvWulFe1BQqs82txvRUPWFtHo98X_M1gEyPNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);